version: '3.5'
services:
        web:
                build: .
                volumes: 
                        - type: bind
                          source: .
                          target: /app
                ports:
                        - "4000:4000"
                command:
                        - ./run.sh
